title = "Work Portfolio: David Stainton"
baseURL = "https://sphinx.rs"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "David Stainton"
  description = "Work Portfolio: David Stainton"
  favicon = ""  # path to a .ico to use as favicon
  avatars_size = "250px"
  [params.footer]
    text = "Copyright 2021 David Stainton"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Resume"
    url = "/david_stainton.pdf"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 2
[[menu.main]]
    name = "Public Speaking"
    url = "/publicspeaking/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 6
  [[menu.main]]
    name = "Mentorships"
    url = "/mentorships/"
    weight = 7
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 8

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
